// !!! This is a file automatically generated by hipify!!!
#include <ATen/hip/HIPContext.h>
#include <ATen/hip/detail/DeviceThreadHandles.h>

namespace at { namespace cuda {
namespace {

void createCusparseHandle(hipsparseHandle_t *handle) {
  TORCH_CUDASPARSE_CHECK(hipsparseCreate(handle));
}

void destroyCusparseHandle(hipsparseHandle_t handle) {
// this is because of something dumb in the ordering of
// destruction. Sometimes atexit, the cuda context (or something)
// would already be destroyed by the time this gets destroyed. It
// happens in fbcode setting. @colesbury and @soumith decided to not destroy
// the handle as a workaround.
//   - Comments of @soumith copied from cuDNN handle pool implementation
#ifdef NO_CUDNN_DESTROY_HANDLE
#else
    hipsparseDestroy(handle);
#endif
}

using CuSparsePoolType = DeviceThreadHandlePool<hipsparseHandle_t, createCusparseHandle, destroyCusparseHandle>;

} // namespace

hipsparseHandle_t getCurrentCUDASparseHandle() {
  int device;
  AT_CUDA_CHECK(hipGetDevice(&device));

  // Thread local PoolWindows are lazily-initialized
  // to avoid initialization issues that caused hangs on Windows.
  // See: https://github.com/pytorch/pytorch/pull/22405
  // This thread local unique_ptrs will be destroyed when the thread terminates,
  // releasing its reserved handles back to the pool.
  static auto pool = std::make_shared<CuSparsePoolType>();
  thread_local std::unique_ptr<CuSparsePoolType::PoolWindow> myPoolWindow(
      pool->newPoolWindow());

  auto handle = myPoolWindow->reserve(device);
  hipsparseSetStream(handle, c10::hip::getCurrentHIPStreamMasqueradingAsCUDA());
  return handle;
}

}} // namespace at::cuda
