// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <ATen/hip/Exceptions.h>

#include <hip/hip_runtime.h>
#include <hip/hip_runtime.h>

namespace at {
namespace cuda {

inline Device getDeviceFromPtr(void* ptr) {
  hipPointerAttribute_t attr;
  AT_CUDA_CHECK(hipPointerGetAttributes(&attr, ptr));
  return {DeviceType::CUDA, static_cast<DeviceIndex>(attr.device)};
}

}} // namespace at::cuda
