// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <ATen/hip/ATenHIPGeneral.h>
#include <ATen/hip/HIPContext.h>
#include <ATen/hip/impl/HIPStreamMasqueradingAsCUDA.h>
#include <ATen/hip/impl/HIPGuardImplMasqueradingAsCUDA.h>
#include <ATen/hip/Exceptions.h>
#include <c10/util/Exception.h>

#include <hip/hip_runtime_api.h>

#include <cstdint>
#include <utility>

namespace at { namespace cuda {

/*
* CUDAEvents are movable not copyable wrappers around CUDA's events.
*
* CUDAEvents are constructed lazily when first recorded unless it is
* reconstructed from a hipIpcEventHandle_t. The event has a device, and this
* device is acquired from the first recording stream. However, if reconstructed
* from a handle, the device should be explicitly specified; or if ipc_handle() is
* called before the event is ever recorded, it will use the current device.
* Later streams that record the event must match this device.
*/
struct TORCH_CUDA_CPP_API CUDAEvent {
  // Constructors
  // Default value for `flags` is specified below - it's hipEventDisableTiming
  CUDAEvent() {}
  CUDAEvent(unsigned int flags) : flags_{flags} {}

  CUDAEvent(
      DeviceIndex device_index, const hipIpcEventHandle_t* handle) {
    #ifndef __HIP_PLATFORM_HCC__
      device_index_ = device_index;
      HIPGuardMasqueradingAsCUDA guard(device_index_);

      AT_CUDA_CHECK(hipIpcOpenEventHandle(&event_, *handle));
      is_created_ = true;
    #else
      AT_ERROR("hipIpcOpenEventHandle with HIP is not supported");
    #endif
  }

  // Note: event destruction done on creating device to avoid creating a
  // CUDA context on other devices.
  ~CUDAEvent() {
    try {
      if (is_created_) {
        HIPGuardMasqueradingAsCUDA guard(device_index_);
        hipEventDestroy(event_);
      }
    } catch (...) { /* No throw */ }
  }

  CUDAEvent(const CUDAEvent&) = delete;
  CUDAEvent& operator=(const CUDAEvent&) = delete;

  CUDAEvent(CUDAEvent&& other) { moveHelper(std::move(other)); }
  CUDAEvent& operator=(CUDAEvent&& other) {
    moveHelper(std::move(other));
    return *this;
  }

  operator hipEvent_t() const { return event(); }

  // Less than operator (to allow use in sets)
  friend bool operator<(const CUDAEvent& left, const CUDAEvent& right) {
    return left.event_ < right.event_;
  }

  optional<at::Device> device() const {
    if (is_created_) {
      return at::Device(at::kCUDA, device_index_);
    } else {
      return {};
    }
  }

  bool isCreated() const { return is_created_; }
  DeviceIndex device_index() const {return device_index_;}
  hipEvent_t event() const { return event_; }

  // Note: hipEventQuery can be safely called from any device
  bool query() const {
    if (!is_created_) {
      return true;
    }

    hipError_t err = hipEventQuery(event_);
    if (err == hipSuccess) {
      return true;
    } else if (err != hipErrorNotReady) {
      C10_HIP_CHECK(err);
    } else {
      // ignore and clear the error if not ready
      hipGetLastError();
    }

    return false;
  }

  void record() { record(getCurrentHIPStreamMasqueradingAsCUDA()); }

  void recordOnce(const HIPStreamMasqueradingAsCUDA& stream) {
    if (!was_recorded_) record(stream);
  }

  // Note: hipEventRecord must be called on the same device as the event.
  void record(const HIPStreamMasqueradingAsCUDA& stream) {
    if (!is_created_) {
      createEvent(stream.device_index());
    }

    TORCH_CHECK(device_index_ == stream.device_index(), "Event device ", device_index_,
      " does not match recording stream's device ", stream.device_index(), ".");
    HIPGuardMasqueradingAsCUDA guard(device_index_);
    AT_CUDA_CHECK(hipEventRecord(event_, stream));
    was_recorded_ = true;
  }

  // Note: hipStreamWaitEvent must be called on the same device as the stream.
  // The event has no actual GPU resources associated with it.
  void block(const HIPStreamMasqueradingAsCUDA& stream) {
    if (is_created_) {
      HIPGuardMasqueradingAsCUDA guard(stream.device_index());
      AT_CUDA_CHECK(hipStreamWaitEvent(stream, event_, 0));
    }
  }

  // Note: hipEventElapsedTime can be safely called from any device
  float elapsed_time(const CUDAEvent& other) const {
    TORCH_CHECK(is_created_ && other.isCreated(),
      "Both events must be recorded before calculating elapsed time.");
    float time_ms = 0;
    // raise hipErrorNotReady if either event is recorded but not yet completed
    AT_CUDA_CHECK(hipEventElapsedTime(&time_ms, event_, other.event_));
    return time_ms;
  }

  // Note: hipEventSynchronize can be safely called from any device
  void synchronize() const {
    if (is_created_) {
      AT_CUDA_CHECK(hipEventSynchronize(event_));
    }
  }

  // Note: hipIpcGetEventHandle must be called on the same device as the event
  void ipc_handle(hipIpcEventHandle_t * handle) {
    #ifndef __HIP_PLATFORM_HCC__
      if (!is_created_) {
        // this CUDAEvent object was initially constructed from flags but event_
        // is not created yet.
        createEvent(getCurrentHIPStreamMasqueradingAsCUDA().device_index());
      }
      HIPGuardMasqueradingAsCUDA guard(device_index_);
      AT_CUDA_CHECK(hipIpcGetEventHandle(handle, event_));
    #else
      AT_ERROR("hipIpcGetEventHandle with HIP is not supported");
    #endif
  }

private:
  unsigned int flags_ = hipEventDisableTiming;
  bool is_created_ = false;
  bool was_recorded_ = false;
  DeviceIndex device_index_ = -1;
  hipEvent_t event_{};

  void createEvent(DeviceIndex device_index) {
    device_index_ = device_index;
    HIPGuardMasqueradingAsCUDA guard(device_index_);
    AT_CUDA_CHECK(hipEventCreateWithFlags(&event_, flags_));
    is_created_ = true;
  }

  void moveHelper(CUDAEvent&& other) {
    std::swap(flags_, other.flags_);
    std::swap(is_created_, other.is_created_);
    std::swap(was_recorded_, other.was_recorded_);
    std::swap(device_index_, other.device_index_);
    std::swap(event_, other.event_);
  }
};

} // namespace cuda
} // namespace at
