// !!! This is a file automatically generated by hipify!!!
#include <gtest/gtest.h>

#include <c10/hip/impl/HIPTest.h>

using namespace c10::hip::impl;

TEST(HIPTest, SmokeTest) {
  c10_hip_test();
}
