// !!! This is a file automatically generated by hipify!!!
#include "caffe2/contrib/aten/aten_op.h"
#include "caffe2/core/hip/context_gpu.h"

namespace caffe2 {

REGISTER_HIP_OPERATOR(ATen, ATenOp<HIPContext>);
template<>
at::Backend ATenOp<HIPContext>::backend() const {
  return at::Backend::HIP;
}

}
