// !!! This is a file automatically generated by hipify!!!
#ifndef THC_GENERIC_FILE
#define THC_GENERIC_FILE "THH/generic/THHTensorMathPairwise.h"
#else

TORCH_CUDA_CU_API int THCTensor_(
    equal)(THCState* state, THCTensor* self, THCTensor* src);

#if !defined(THC_REAL_IS_BOOL)

TORCH_CUDA_CU_API void THCTensor_(
    mul)(THCState* state, THCTensor* self, THCTensor* src, scalar_t value);

#endif

#endif
