// !!! This is a file automatically generated by hipify!!!
#include <c10/hip/HIPFunctions.h>
#include <c10/macros/Macros.h>

#include <limits>

namespace c10 {
namespace hip {

namespace {
// returns -1 on failure
int32_t driver_version() {
  int driver_version = -1;
  hipError_t err = hipDriverGetVersion(&driver_version);
  if (err != hipSuccess) {
    hipError_t last_err C10_UNUSED = hipGetLastError();
  }
  return driver_version;
}

int device_count_impl(bool fail_if_no_driver) {
  int count;
  auto err = hipGetDeviceCount(&count);
  if (err == hipSuccess) {
    return count;
  }
  // Clear out the error state, so we don't spuriously trigger someone else.
  // (This shouldn't really matter, since we won't be running very much HIP
  // code in this regime.)
  hipError_t last_err C10_UNUSED = hipGetLastError();
  switch (err) {
    case hipErrorNoDevice:
      // Zero devices is ok here
      count = 0;
      break;
    case hipErrorInsufficientDriver: {
      auto version = driver_version();
      if (version <= 0) {
        if (!fail_if_no_driver) {
          // No HIP driver means no devices
          count = 0;
          break;
        }
        TORCH_CHECK(
            false,
            "Found no NVIDIA driver on your system. Please check that you "
            "have an NVIDIA GPU and installed a driver from "
            "http://www.nvidia.com/Download/index.aspx");
      } else {
        TORCH_CHECK(
            false,
            "The NVIDIA driver on your system is too old (found version ",
            version,
            "). Please update your GPU driver by downloading and installing "
            "a new version from the URL: "
            "http://www.nvidia.com/Download/index.aspx Alternatively, go to: "
            "https://pytorch.org to install a PyTorch version that has been "
            "compiled with your version of the HIP driver.");
      }
    } break;
    case hipErrorInitializationError:
      TORCH_CHECK(
          false,
          "HIP driver initialization failed, you might not "
          "have a HIP gpu.");
      break;
    case hipErrorUnknown:
      TORCH_CHECK(
          false,
          "HIP unknown error - this may be due to an "
          "incorrectly set up environment, e.g. changing env "
          "variable HIP_VISIBLE_DEVICES after program start. "
          "Setting the available devices to be zero.");
      break;
#if C10_ASAN_ENABLED
    case hipErrorMemoryAllocation:
      // In ASAN mode, we know that a hipErrorMemoryAllocation error will
      // pop up if compiled with NVCC (clang-cuda is fine)
      TORCH_CHECK(
          false,
          "Got 'out of memory' error while trying to initialize HIP. "
          "HIP with nvcc does not work well with ASAN and it's probably "
          "the reason. We will simply shut down HIP support. If you "
          "would like to use GPUs, turn off ASAN.");
      break;
#endif // C10_ASAN_ENABLED
    default:
      TORCH_CHECK(
          false,
          "Unexpected error from hipGetDeviceCount(). Did you run "
          "some cuda functions before calling NumHipDevices() "
          "that might have already set an error? Error ",
          err,
          ": ",
          hipGetErrorString(err));
  }
  return count;
}
} // namespace

DeviceIndex device_count() noexcept {
  // initialize number of devices only once
  static int count = []() {
    try {
      auto result = device_count_impl(/*fail_if_no_driver=*/false);
      TORCH_INTERNAL_ASSERT(
          result <= std::numeric_limits<DeviceIndex>::max(),
          "Too many HIP devices, DeviceIndex overflowed");
      return result;
    } catch (const c10::Error& ex) {
      // We don't want to fail, but still log the warning
      // msg() returns the message without the stack trace
      TORCH_WARN("HIP initialization: ", ex.msg());
      return 0;
    }
  }();
  return static_cast<DeviceIndex>(count);
}

DeviceIndex device_count_ensure_non_zero() {
  // Call the implementation every time to throw the exception
  int count = device_count_impl(/*fail_if_no_driver=*/true);
  // Zero gpus doesn't produce a warning in `device_count` but we fail here
  TORCH_CHECK(count, "No HIP GPUs are available");
  return static_cast<DeviceIndex>(count);
}

DeviceIndex current_device() {
  int cur_device;
  C10_HIP_CHECK(hipGetDevice(&cur_device));
  return static_cast<DeviceIndex>(cur_device);
}

void set_device(DeviceIndex device) {
  C10_HIP_CHECK(hipSetDevice(static_cast<int>(device)));
}

void device_synchronize() {
  C10_HIP_CHECK(hipDeviceSynchronize());
}

// this function has to be called from callers performing cuda synchronizing
// operations, to raise proper error or warning
void warn_or_error_on_sync() {
  if (warning_state().get_sync_debug_mode() == SyncDebugMode::L_ERROR) {
    TORCH_CHECK(false, "called a synchronizing HIP operation");
  } else if (warning_state().get_sync_debug_mode() == SyncDebugMode::L_WARN) {
    TORCH_WARN("called a synchronizing HIP operation");
  }
}

} // namespace hip
} // namespace c10
