// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <c10/hip/HIPStream.h>
#include <utility>

// HIP Graphs utils used by c10 and aten.
// aten/cuda/HIPGraphsUtils.cuh adds utils used by aten only.

namespace c10 {
namespace hip {

using CaptureId_t = unsigned long long;

// first is set if the instance is created by HIPGraph::capture_begin.
// second is set if the instance is created by at::cuda::graph_pool_handle.
using MempoolId_t = std::pair<CaptureId_t, CaptureId_t>;

// RAII guard for "cudaStreamCaptureMode", a thread-local value
// that controls the error-checking strictness of a capture.
#if HIP_VERSION >= 11000
struct C10_HIP_API HIPStreamCaptureModeGuard {
  HIPStreamCaptureModeGuard(cudaStreamCaptureMode desired) {
    strictness_ = desired;
    C10_HIP_CHECK(cudaThreadExchangeStreamCaptureMode(&strictness_));
  }
  ~HIPStreamCaptureModeGuard() {
    C10_HIP_CHECK_WARN(cudaThreadExchangeStreamCaptureMode(&strictness_));
  }

 private:
  cudaStreamCaptureMode strictness_;
};
#endif

#if defined(HIP_VERSION) && HIP_VERSION >= 11000
// Protects against enum cudaStreamCaptureStatus implementation changes.
// Some compilers seem not to like static_assert without the messages.
static_assert(
    int(cudaStreamCaptureStatus::cudaStreamCaptureStatusNone) == 0,
    "unexpected int(cudaStreamCaptureStatusNone) value");
static_assert(
    int(cudaStreamCaptureStatus::cudaStreamCaptureStatusActive) == 1,
    "unexpected int(cudaStreamCaptureStatusActive) value");
static_assert(
    int(cudaStreamCaptureStatus::cudaStreamCaptureStatusInvalidated) == 2,
    "unexpected int(cudaStreamCaptureStatusInvalidated) value");
#endif

enum class CaptureStatus : int {
#if defined(HIP_VERSION) && HIP_VERSION >= 11000
  None = int(cudaStreamCaptureStatus::cudaStreamCaptureStatusNone),
  Active = int(cudaStreamCaptureStatus::cudaStreamCaptureStatusActive),
  Invalidated = int(cudaStreamCaptureStatus::cudaStreamCaptureStatusInvalidated)
#else
  None = 0
#endif
};

inline std::ostream& operator<<(std::ostream& os, CaptureStatus status) {
  switch (status) {
    case CaptureStatus::None:
      os << "cudaStreamCaptureStatusNone";
      break;
#if defined(HIP_VERSION) && HIP_VERSION >= 11000
    case CaptureStatus::Active:
      os << "cudaStreamCaptureStatusActive";
      break;
    case CaptureStatus::Invalidated:
      os << "cudaStreamCaptureStatusInvalidated";
      break;
#endif
    default:
      TORCH_INTERNAL_ASSERT(
          false, "Unknown HIP graph CaptureStatus", int(status));
  }
  return os;
}

// Use this version where you're sure a HIP context exists already.
inline CaptureStatus currentStreamCaptureStatusMayInitCtx() {
#if defined(HIP_VERSION) && HIP_VERSION >= 11000
  cudaStreamCaptureStatus is_capturing;
  C10_HIP_CHECK(
      cudaStreamIsCapturing(c10::hip::getCurrentHIPStream(), &is_capturing));
  return CaptureStatus(is_capturing);
#else
  return CaptureStatus::None;
#endif
}

} // namespace hip
} // namespace c10
