// !!! This is a file automatically generated by hipify!!!
#include <THH/THH.h>

#define THCIndexTensor THCudaLongTensor
#define THCIndexTensor_(NAME) THCudaLongTensor_ ## NAME
typedef int64_t THCIndex_t;

#define THNN_(NAME) TH_CONCAT_3(THNN_, CReal, NAME)

#include <THHUNN/generic/THHUNN.h>
#include <THH/THHGenerateFloatTypes.h>

#include <THHUNN/generic/THHUNN.h>
#include <THH/THHGenerateBFloat16Type.h>
