// !!! This is a file automatically generated by hipify!!!
#ifndef THC_INC
#define THC_INC

#include <THH/THHGeneral.h>
#include <THH/THHAllocator.h>
#include <ATen/hip/impl/HIPCachingAllocatorMasqueradingAsCUDA.h>
#include <THH/THHCachingHostAllocator.h>
#include <THH/THHSleep.h>
#include <THH/THHStorage.h>
#include <THH/THHStorageCopy.h>

#include <THH/THHTensor.h>
#include <THH/THHTensorCopy.h>
#include <THH/THHTensorMath.h>

#endif
