// !!! This is a file automatically generated by hipify!!!
#ifndef THC_GENERIC_FILE
#error "You must define THC_GENERIC_FILE before including THCGenerateComplexTypes.h"
#endif

#define THCGenerateComplexTypes

#include <THH/THHGenerateComplexFloatType.h>
#include <THH/THHGenerateComplexDoubleType.h>

#undef THCGenerateComplexTypes
#undef THC_GENERIC_FILE
