// !!! This is a file automatically generated by hipify!!!
#ifndef THC_GENERAL_INC
#define THC_GENERAL_INC

#include <TH/THGeneral.h>

#include <c10/core/Allocator.h>
#include <ATen/hip/impl/HIPStreamMasqueradingAsCUDA.h>

#include <hip/hip_runtime.h>
#include <hip/hip_runtime.h>
#include <rocblas.h>

#include <hipsparse.h>

/* Global state of THC. */
struct THCState {};

#endif
