// !!! This is a file automatically generated by hipify!!!
#include <THH/THHStorageCopy.h>
#include <THH/THHTensor.hpp>

#include <THH/THHTensorCopy.h>

#include <THH/generic/THHStorageCopy.cpp>
#include <THH/THHGenerateAllTypes.h>

#include <THH/generic/THHStorageCopy.cpp>
#include <THH/THHGenerateComplexTypes.h>

#include <THH/generic/THHStorageCopy.cpp>
#include <THH/THHGenerateBoolType.h>

#include <THH/generic/THHStorageCopy.cpp>
#include <THH/THHGenerateBFloat16Type.h>
