// !!! This is a file automatically generated by hipify!!!
#ifndef THC_STORAGE_COPY_INC
#define THC_STORAGE_COPY_INC

#include <THH/THHStorage.h>
#include <THH/THHGeneral.h>
#include <TH/THHalf.h>

#include <THH/generic/THHStorageCopy.h>
#include <THH/THHGenerateAllTypes.h>

#include <THH/generic/THHStorageCopy.h>
#include <THH/THHGenerateComplexTypes.h>

#include <THH/generic/THHStorageCopy.h>
#include <THH/THHGenerateBoolType.h>

#include <THH/generic/THHStorageCopy.h>
#include <THH/THHGenerateBFloat16Type.h>

#endif
