// !!! This is a file automatically generated by hipify!!!
#ifndef TH_CUDA_TENSOR_COPY_INC
#define TH_CUDA_TENSOR_COPY_INC

#include <THH/THHTensor.h>
#include <THH/THHGeneral.h>
#include <TH/THHalf.h>

#include <THH/generic/THHTensorCopy.h>
#include <THH/THHGenerateAllTypes.h>

#include <THH/generic/THHTensorCopy.h>
#include <THH/THHGenerateComplexTypes.h>

#include <THH/generic/THHTensorCopy.h>
#include <THH/THHGenerateBoolType.h>

#include <THH/generic/THHTensorCopy.h>
#include <THH/THHGenerateBFloat16Type.h>

#endif
