// !!! This is a file automatically generated by hipify!!!
#ifndef THC_TENSOR_INC
#define THC_TENSOR_INC

#include <TH/THTensor.h>
#include <THH/THHStorage.h>
#include <THH/THHGeneral.h>

#define THCTensor_(NAME)   TH_CONCAT_4(TH,CReal,Tensor_,NAME)

#define THC_DESC_BUFF_LEN 64

typedef struct TORCH_CUDA_CU_API THCDescBuff {
  char str[THC_DESC_BUFF_LEN];
} THCDescBuff;

#include <THH/generic/THHTensor.h>
#include <THH/THHGenerateAllTypes.h>

#include <THH/generic/THHTensor.h>
#include <THH/THHGenerateComplexTypes.h>

#include <THH/generic/THHTensor.h>
#include <THH/THHGenerateBoolType.h>

#include <THH/generic/THHTensor.h>
#include <THH/THHGenerateBFloat16Type.h>

#endif
