// !!! This is a file automatically generated by hipify!!!
#ifndef TH_CUDA_TENSOR_MATH_INC
#define TH_CUDA_TENSOR_MATH_INC

#include <THH/THHTensor.h>
#include <THH/THHGeneral.h>

#include <THH/generic/THHTensorMath.h>
#include <THH/THHGenerateAllTypes.h>

#include <THH/generic/THHTensorMath.h>
#include <THH/THHGenerateBoolType.h>

#include <THH/generic/THHTensorMath.h>
#include <THH/THHGenerateBFloat16Type.h>

#include <THH/generic/THHTensorMathMagma.h>
#include <THH/THHGenerateAllTypes.h>

#include <THH/generic/THHTensorMathPairwise.h>
#include <THH/THHGenerateAllTypes.h>

#include <THH/generic/THHTensorMathPairwise.h>
#include <THH/THHGenerateBoolType.h>

#include <THH/generic/THHTensorScatterGather.h>
#include <THH/THHGenerateAllTypes.h>

#include <THH/generic/THHTensorScatterGather.h>
#include <THH/THHGenerateBoolType.h>

#endif
