// !!! This is a file automatically generated by hipify!!!
#include <THH/THHGeneral.h>
#include <THH/THHTensorMath.h>
#include <THH/THHTensorCopy.h>
#include <THH/THHTensorMathMagma.h>
#include <THH/THHTensor.hpp>
#include <THH/THHStorage.hpp>
#include <algorithm>
#include <ATen/native/hip/MiscUtils.h>
#include <ATen/hip/detail/HIPHooks.h>

#ifdef USE_MAGMA
#include <magma_v2.h>
#endif

#ifndef DIVUP
#define DIVUP(x, y) (((x) + (y) - 1) / (y))
#endif

#define NoMagma(name) "No CUDA implementation of '" #name "'. Install MAGMA and rebuild cutorch (http://icl.cs.utk.edu/magma/)"

namespace {
void _THCMagma_init() {
#ifdef USE_MAGMA
  magma_init();
#endif
}

struct Initializer {
  Initializer() {
    ::at::cuda::detail::THCMagma_init = _THCMagma_init;
  };
} initializer;
} // anonymous namespace

#include <THH/generic/THHTensorMathMagma.cpp>
#include <THH/THHGenerateAllTypes.h>
