// !!! This is a file automatically generated by hipify!!!
#include <c10/hip/impl/HIPGuardImpl.h>

namespace c10 {
namespace hip {
namespace impl {

constexpr DeviceType HIPGuardImpl::static_type;

C10_REGISTER_GUARD_IMPL(HIP, HIPGuardImpl);

} // namespace impl
} // namespace hip
} // namespace c10
