// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <c10/hip/HIPMacros.h>

namespace c10 {
namespace hip {
namespace impl {

C10_HIP_API int c10_hip_test();

}
} // namespace hip
} // namespace c10
