// !!! This is a file automatically generated by hipify!!!
#include "caffe2/core/hip/context_gpu.h"
#include "caffe2/operators/rnn/recurrent_network_blob_fetcher_op.h"

namespace caffe2 {
REGISTER_HIP_OPERATOR(
    RecurrentNetworkBlobFetcher,
    RecurrentNetworkBlobFetcherOp<HIPContext>);
} // namespace caffe2
