// !!! This is a file automatically generated by hipify!!!
#include "caffe2/operators/do_op.h"

#include "caffe2/core/hip/context_gpu.h"

namespace caffe2 {

REGISTER_HIP_OPERATOR(Do, DoOp<HIPContext>);

} // namespace caffe2
