// !!! This is a file automatically generated by hipify!!!
#include "caffe2/operators/elementwise_op_test.h"

#include "caffe2/core/hip/context_gpu.h"
#include "caffe2/core/flags.h"

C10_DECLARE_string(caffe_test_root);

template <>
void CopyVector<caffe2::HIPContext>(const int N, const bool* x, bool* y) {
  HIP_CHECK(hipMemcpy(y, x, N * sizeof(bool), hipMemcpyHostToDevice));
}

template <>
caffe2::OperatorDef CreateOperatorDef<caffe2::HIPContext>() {
  caffe2::OperatorDef def;
  def.mutable_device_option()->set_device_type(caffe2::PROTO_HIP);
  return def;
}

TEST(ElementwiseGPUTest, And) {
  if (!caffe2::HasHipGPU())
    return;
  elementwiseAnd<caffe2::HIPContext>();
}

TEST(ElementwiseGPUTest, Or) {
  if (!caffe2::HasHipGPU())
    return;
  elementwiseOr<caffe2::HIPContext>();
}

TEST(ElementwiseGPUTest, Xor) {
  if (!caffe2::HasHipGPU())
    return;
  elementwiseXor<caffe2::HIPContext>();
}

TEST(ElementwiseGPUTest, Not) {
  if (!caffe2::HasHipGPU())
    return;
  elementwiseNot<caffe2::HIPContext>();
}
