// !!! This is a file automatically generated by hipify!!!
#include "caffe2/core/hip/context_gpu.h"
#include "caffe2/operators/free_op.h"

namespace caffe2 {
REGISTER_HIP_OPERATOR(Free, FreeOp<HIPContext>);
} // namespace caffe2
