// !!! This is a file automatically generated by hipify!!!
#include "caffe2/operators/log_op.h"

#include "caffe2/core/hip/context_gpu.h"

namespace caffe2 {

REGISTER_HIP_OPERATOR(
    Log,
    UnaryElementwiseOp<
        TensorTypes<float>,
        HIPContext,
        LogFunctor<HIPContext>>);

} // namespace caffe2
