// !!! This is a file automatically generated by hipify!!!
#include "caffe2/core/hip/context_gpu.h"
#include "caffe2/operators/shape_op.h"

namespace caffe2 {
REGISTER_HIP_OPERATOR(Shape, ShapeOp<HIPContext>);
}
