// !!! This is a file automatically generated by hipify!!!
#include "caffe2/core/hip/context_gpu.h"
#include "caffe2/operators/stop_gradient.h"

namespace caffe2 {
REGISTER_HIP_OPERATOR(StopGradient, StopGradientOp<HIPContext>);
}  // namespace caffe2
